### ISSUE TITLE
Scan Report Index

### ISSUE THREAD

**Issue by blargly** [Health-Informatics-UoN/CaRROT-Mapper#649]
# Summary

A test case to reimplement the Scan Report index page in NextJS. This is to test the viability of this approach before rewriting other pages.
This work is needed in order pave the way for revamping other pages and reducing technical debt across the front end and APIs.

# Tasks

- [x] Create Next App
- [x] Local Dev Experience
- [x] Auth
- [x] Page
- [x] CSS Styles
- [x] Fetch scan reports
- [x] Table
- [x] Routing Investigation for Azure
- [x] Deployment
- [x] Fix proxy pages to be limited to `/scanreport/` (probably change the URL ordering)
- [ ] Review

# Acceptance Criteria

- [x] Deployed instance of CARROT with this feature
- [x] Functionality is unchanged
- [x] Appearance is unchanged

**Comment by AndyRae** [comment]
Completed in #691

**Comment by AndyRae** [comment]
Other feedback, beyond the existing bugs:

- [ ] Add the ID column back
