### ISSUE TITLE
CSV Export updates

### ISSUE THREAD

**Issue by blargly** [Health-Informatics-UoN/CaRROT-Mapper#650]
# Summary

Note: requested by Esmond Urwin and Phil Quinlan

The current CSV export could do with improvement - column order, column names, and a few other properties would be of value as extra columns. 

# Tasks

- [ ] Rename the following columns:
    - [ ] concept to concept_id
    - [ ] rule_name to omop_term
    - [ ] destination_field to domain
 
- [ ] Add the following columns:
    - [ ] class
    - [ ] concept
    - [ ] validity
    - [ ] vocabulary

- [ ] Rearrange column order: source_table | source_field | source_value | concept_id | omop_term | class | concept | validity | domain | vocabulary | creation_type | rule_id | isFieldMapping

- [ ] Add export to Excel option. This will be the same as the CSV export but export to the Excel file type. This will help with opening files in certain locales.

# Acceptance Criteria

- [ ] CSV download has a new order, new columns, renamed columns
- [ ] New Excel download, matches columns of CSV
