### ISSUE TITLE
Django ORM use with Azure Functions

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/CaRROT-Mapper#662]
# Summary

We need to use the Django ORM inside the web app, but also with Azure Functions.

Effectively a "data" library that is packaged with both.

Relevant to: #612 

# Tasks

- [x] Create data library
- [x] Integrate this with Django App
- [x] Integrate this with Azure Functions

# Acceptance Criteria

- [x] Deployed Azure function can use the database directly
- [x] Deployed Django web app can still use the database directly
- [x] Tests pass
