### ISSUE TITLE
Mapping Rules Azure Function

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/CaRROT-Mapper#663]
# Summary

Add an Azure function to generate mapping rules.

Make Mapping Rules happen on a table basis.
Take a list of Scan Reports that should be reused. If there is no Scan Reports passed, just use them all. (#623) (I'm not sure, but assume this probably has to happen earlier in the mapping process)

Relevant to: #612 

We will retain the existing "Refresh Rules" button for now, as a fallback option. 

# Tasks

- [x] New Azure Function
- [x] Generate mapping rules (port existing code)
- [x] Add the trigger from re use of mapping rules

# Acceptance Criteria

- [x] Mapping rules are generated with Azure functions
- [x] Tests pass
