### ISSUE TITLE
Scan Report Index - Split out Status Columns

### ISSUE THREAD

**Issue by blargly** [Health-Informatics-UoN/Carrot-Mapper#696]
# Summary

While the investigation into the Azure based routing is ongoing, we can proceed with splitting out the column functionality. Status now should be: Status and Estimated Mapping Progress. 

Status is split into Uploading, Upload Failed, Awaiting Table Ids, Processing, Failed Processing, Done. This is set automatically by the app, depending on the upload and processing progress.

Mapping Progress is: 0%., 25%, 50%. 75% and Complete. Defaults to 0. This is set manually by the user. This the column used to check for "Mapping Complete".

We will need 2 new entities, and to seed these in our back end. Do this in the proper way - using Django Fixtures (already in the app_).

# Tasks

- [ ] 2 new entities - NewStatus and MappingProgress.
- [ ] Update ScanReport entity to have 2 new values (the above new entities)
- [ ] Seed the values for these
- [ ] Migrations
- [ ] Serialiser - update this to pull in the list options for mapping.
- [ ] Front end - add the 2 new columns
- [ ] add new properties to ScanReport type
- [ ] Hide Status (old column)
- [ ] Update ScanReport end point to set NewStatus when: file uploads, when file upload fails, when upload finishes, when processing starts, when processing fails, when processing finishes.
- [ ] Review

# Acceptance Criteria

- [ ] Table view, now no longer has old status column, but 2 new columns.
- [ ] (new) status shows new options depending on scan report functions - can't be set by user
- [ ] Mapping is still a drop down with a more limited range than before.

**Comment by AndyRae** [comment]
`mapping_status`

```
PENDING = "PENDING", "Mapping 0%"
IN_PROGRESS_25PERCENT = "INPRO25", "Mapping 25%"
IN_PROGRESS_50PERCENT = "INPRO50", "Mapping 50%"
IN_PROGRESS_75PERCENT = "INPRO75", "Mapping 75%
COMPLETE = "COMPLET", "Mapping Complete"
BLOCKED = "BLOCKED", "Blocked"
```

`upload_status`

```
    UPLOAD_IN_PROGRESS = "UPINPRO", "Upload in Progress"
    UPLOAD_COMPLETE = "UPCOMPL", "Upload Complete"
    UPLOAD_FAILED = "UPFAILE", "Upload Failed"
```

### Db Backend
- [ ] 2 new "status" tables, with the following data to be seeded in, and added as `constants` in the frontend
- [ ] Add the foreign keys to the `ScanReport` model (nullable)
- [ ] Redo migrations
- [ ] Create seed data (manually enter using Datagrip, and `dumpdata` out to `.json`

### Migrate data and make changes

- [ ] Create an empty migration
- [ ] Add `migrate_status_data` custom migration function
- [ ] Update this to be relevant to the newly seeded status tables
     - [ ] Get the `mapping_status`/`upload_status` entity from the database and set it on the `report` model
- [ ] Delete the scan report status
- [ ] Update the migration
- [ ] Add in the rest of the code changes
