### ISSUE TITLE
Delete Scan Report backend

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#729]
## Backend

Add the backend to allow a user to delete a Scan Report.

# Tasks
- [ ] Add a delete method to the scanreport endpoint.
- [ ] Add delete logic for the data. 
- [ ] Add deleting the files in blob storage, both the scan report, and the data dictionary. Consider doing this by a "service" module.
- [ ] Add permissions for only an Owner of a scan report to delete it.
