### ISSUE TITLE
Backend data model for Scan Reports Jobs

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/carrot-mapper#743]
# Summary

Create a backend data model to represent the Scan Reports jobs.

# Tasks

- [ ] Create the Stages model (in the shared library code)
- [ ] Create the Jobs model (in the shared library code)
- [ ] Create migrations
- [ ] Seed the Stages
    - [ ] Update Table
    - [ ] Rules Reuse
- [ ] Review 

Use the basemodel for these:

Stages Model // Is this still necessary??
```
ID: int
Name: string
NextStage: nullable ID
SortOrder: int
```

Jobs Model
```
ID: int
Scan Report ID: Int
Scan Report TableId: Int / Null
CreatedAt: DateTime (from basemodel)
UpdatedAt: DateTime (from basemodel)
Stage: StageId
Status: Id
Details: string
```

# Acceptance Criteria

- [ ] New database tables for the Stages, and Jobs
- [ ] Seeded data for the Stages

**Comment by AndrewThien** [comment]
Jobs Model
```
ID: int
Scan Report ID: Int
Scan Report TableId: Int / Null
CreatedAt: DateTime (from basemodel)
UpdatedAt: DateTime (from basemodel)
Stage: string (Upload SR | Building concepts from OMOP vocabs | Reusing Concepts | Rules Generation | Download Rules)
Status: Id (foreign key to Status model)
Details: string
```

Status model
```
ID: int
Status: String (in progress | completed | failed)
Display_name: string
```
