### ISSUE TITLE
Backend API to get a Scan Reports Jobs

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/carrot-mapper#744]
# Summary

Create API endpoints to allow the frontend to fetch the Scan Reports Jobs.

# Tasks

- [ ] New routers in `routers.py`
- [ ] New serializers in `serializers.py`
- [ ] New endpoints in `views.py`
- [ ] Review

## Summary endpoint:
`scanreports/{id}/jobs`
Given a Scan Report, give a list of Jobs, only containing the Status, and the Stage.
This should only return one Job for each stage, being the latest one.

## Scan Report Table endpoint:
`scanreporttables/{id}/jobs` 
Given a Scan Report table, return a list of Jobs - containing the full model.

# Acceptance Criteria

- [ ] Working endpoints for Scan Report Jobs summary
- [ ] Working endpoints for Scan Report Table Jobs detail list
