### ISSUE TITLE
Update Workers to create/update Scan Report Jobs

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/carrot-mapper#745]
# Summary

Add the Worker Jobs updating the status of their Scan Report Jobs, on beginning, completing, and failing. 
Creation, and failing "might" be only done at the queue level.
Completing probably only happens at the end of the Job.

# Tasks

- [ ] Add creation to the RulesTrigger worker
- [ ] Add failing to the RulesQueue worker, or the RulesOrchestrator
- [ ] Add completion to the RulesOrchestrator

# Acceptance Criteria

- [ ] Jobs now update on their status when they are created, failing, and completed.
