### ISSUE TITLE
UI for Scan Report Jobs Overview

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/carrot-mapper#746]
# Summary

Create a user interface for showing the user the overview of Scan Report Jobs.
The status of each Scan Report Table does not need to link to a modal yet.

## This might be unnecessary - let's look at ways we can incorporate the status into the existing tables. For example, the table list, showing the status of a table mapping. 

# Tasks

- [ ] New page in Next: `/scanreports/2562/jobs`
- [ ] Add data fetching in `api/scanreports.ts` - 
    - [ ] Get the summary of Scan Reports Jobs.
- [ ] Get the data in page, including the summary, and the Scan Report itself.
- [ ] A new data table built from the stages, and displaying the status
- [ ] Add Action to "View Status" to the Scan Report List View data table.

# Acceptance Criteria

- [ ] A page that shows the overview of Scan Report Jobs.
