### ISSUE TITLE
UI for Scan Report Table Job Modal

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/carrot-mapper#747]
# Summary

Create a user interface modal for showing the user the overview of Scan Report Table Jobs.

# Tasks

- [ ] New component in Next: `/scanreports/2562/jobs`
- [ ] Add data fetching in `api/scanreports.ts` - 
    - [ ] Get the list of Scan Report Table Jobs.
- [ ] Get the data in page.
- [ ] A "simple" table displaying the list of jobs
- [ ] Add the button to the "View Status" to the Scan Report Jobs Overview data table.

# Optional Tasks

- [ ] Consider using the Intercepting Routes functionality of Next: https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes

# Acceptance Criteria

- [ ] A modal that shows the overview of Scan Report Table Jobs.
