### ISSUE TITLE
Scan Report Details (edit form)

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#749]
# Summary

Rewrite the Scan Report Details page in Nextjs, for example: https://ccom-dev.azurewebsites.net/scanreports/2565/details/

# Tasks

- [ ] Implement with FormIk
- [ ] Implement the React Select from `New Scan Report` form
- [ ] POST data - same pattern as Add Scan Report table.
- [ ] On form load - populate with the existing data
- [ ] Permissions for a Scan Report - CanAdmin | CanEdit
- [ ] Add information tooltips (this can mirror the `New Scan Report` form
- [ ] Testing

# Acceptance Criteria

- [ ] A working Scan Report Details form, with data posting, and populating.
