### ISSUE TITLE
Scan Report Mapping Rules

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#750]
# Summary

Rewrite the Scan Report Mapping rules page in Nextjs, for example: https://ccom-dev.azurewebsites.net/scanreports/2565/mapping_rules/?p=1&page_size=30

# Tasks

- [ ] New page in Nextjs
- [ ] Add new data fetching for `mapping_rules` and `mappingruleslist`
- [ ] Implement fetching on page (default `page_size` of 30)
- [ ] New data table
- [ ] Do not add filtering or sorting
- [ ] Add buttons (download .csv etc.)
- [ ] Add "view map diagram" (this should also be the endpoint used in the React code)
- [ ] Design
    - [ ] Combine the "Download" buttons into a dropdown (this is an  "outline" button with "actions", on the far right of the page)
    - [ ] Show Summary / Analyse Rules can still be on the far left. 
    - [ ] Consistent with the existing design

# Acceptance Criteria

- [ ] Working Mapping Rules page
- [ ] Working downloads for each button
