### ISSUE TITLE
Generate Vocabularies

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#752]
# Summary

We would like to be able to generate a vocabulary based on a Scan Report, to upload it to Athena. This is an initial proposal, and welcome comments based on it.

Supporting Documentation:

- [Documentation](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Community-contribution:-non%E2%80%90drug-vocabularies-p.I#types-of-contributions) (type 4)
- The [template to generate](https://docs.google.com/spreadsheets/d/1dzcXR6jUg0sBHROffr0F3t6VSes8gQGs/edit#gid=1914212748)

A potential roadmap for versions of this:

## Version 1:
- A small form that enables a user to export vocabularies from a Scan Report. 
- Form asks for the `vocabulary_id` to effectively name the vocabulary, the vocabulary is generated and returned to the user.
- Carrot will build a vocabulary, similar to how it currently exports the mapping_rules to `.csv`
- This all depends on mapping rules existing. 
- This approach leaves the user to complete the `concept_name` column of the template.

## Version 2:
- As above.
- User will supply a `source_dictionary` in the form, this should include at least 2 columns, a  mapping from the `concept_code` to the `concept_name`, which is effectively a description of the vocabulary term. 
- Carrot uses this to populate the `concept_name` of the template
- We can either define a template for this form, or allow a user to upload a spreadsheet, and let them select which columns contain the code/name.

## Caveats
We will need to be clear to the user, that there are limitations to this export and it depends on:
- The Scan Report minimum cell count (truncation) of White Rabbit. Data might have been lost, so therefore there cannot be a complete vocabulary of it.
- The need for QA checking of the export  

# Tasks
- [ ] Backend - export vocabulary service.
- [ ] Frontend - a form to support exporting the vocabulary.

# Acceptance Criteria
- [ ] A way for the user to export vocabulary information from a Scan Report.
