### ISSUE TITLE
Containerise the Next.js project

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#804]
## Tasks  

- [ ] New Dockerfile
- [ ] Mount the current code directory for the `app/next-client-app`
- [ ] Install npm dependencies
- [ ] Add to `docker-compose`
- [ ] Move `.env` configuration upwards to the Docker Compose
    - [ ] Web backend config
    - [ ] Nextjs .env config  

Use existing templates
