### ISSUE TITLE
Containerise the Azure Functions

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#805]
## Tasks

- [ ] New Dockerfile
- [ ] Mount the code directory
- [ ] Install Poetry
- [ ] Install Python dependencies
- [ ] Add to `docker-compose`
- [ ] Move .env configuration upwards to the Docker Compose
