### ISSUE TITLE
Uncouple V2 endpoints

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#806]
The future of the API is in the V2 endpoints, we would like to be able to cleanly delete V1 in the future.

Some of the V2 endpoints are subclasses of V1, we should now unsubclass them - so V1 is easier to remove.

## Tasks
- [ ] Move the missing methods, and properties to the V2 endpoint
- [ ] Change the subclass to `ModelViewSet` or what the original V1 is subclassed on.
- [ ] Test
- [ ] Remove ScanReportListViewV2 `get_queryset`:
    - [ ] Replace it with `ScanReportAccessFilter` as a filter backend
    - [ ] Test permissions, can users see only the scan reports they should.

Endpoints:
- [ ] ScanReportListViewSetV2
- [ ] ScanReportTableViewSetV2
- [ ] ScanReportFieldViewSetV2
