### ISSUE TITLE
Carrot Landing Page

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#825]
It would be really nice to have this for commencing marketing for the OMOP conference :)

(End of August?)

## Tasks

- [x] #826
- [x] #827
- [x] Technical SEO / Marketing implementation
- [x] Refined version

## Discussion
- [x] Branding:
     - [x] University in footer
     - [x] Funders, part of the story (Co-Connect, and beyond...) 
- [ ] About page (?), including the team 
- [ ] Analytics (?)

The initial version of this is going to be simple, a way to begin to improve perception.
We expect a couple of initial options, that we will then refine further.

## Call To Action
Currently there is no direct action - a user cannot sign up to Carrot.
Options:
- Contact us (request access ((link to...)
- Self host (deploy your own (link to deployment docs))
- Join our community (link to Github Discussions (branded button))
- Attend our event ((link to conference))
- User registration (future)

[Initial design ](https://whiteboard.office.com/me/whiteboards/p/c3BvOmh0dHBzOi8vdW5pb2Zub3R0bS1teS5zaGFyZXBvaW50LmNvbS9wZXJzb25hbC9hbmR5X3JhZV9ub3R0aW5naGFtX2FjX3Vr/b!mAc72Dvk6UuVmxWuetQtl8zmGUHZCmRMuk2mkR3EwGnrX1IFgGvfTomSDAHImloJ/01BCY66MG3H3DXUKHCZZH3NG3I2FBLTUDQ?source=applauncher&auth_upn=andy.rae%40nottingham.ac.uk)

## Programme / Funders:
- Nottingham BRC, NIHR
- EMSDE - NHS England
- ByCovid - EU / Horizon
- Alleviate - UKRI
- CoConnect - UKRI, NIHR 

## Examples:
https://stripe.com/gb 
https://www.paypal.com/uk/home
https://nextjs.org/
https://www.figma.com/ai/
https://mubi.com/en/gb

## Where should link to this site, for information, and SEO reasons?
- Existing CMS for BRC - where we put RedCap etc. 
- Add to the Health Informatics Sharepoint site
- Fed A site
