### ISSUE TITLE
Datasets filter by Project API

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#892]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Adding `Projects` to the dataset API, so that `datasets_data_partners` can be filtered by projects.

`?project_id__in=123`

### Acceptance Criteria

- [ ] A backend API for a list of datasets filtered to a project.
- [ ] Tests pass.

### Tasks

- [ ] Update `DatasetAndDataPartnerViewSerializer` serialiser code. In this instance, it is fine for just the ID of the project to be serialised.
- [ ] Update `DatasetAndDataPartnerListView` add `Projects` to the existing filtering.

### Confirm creation

- [x] This issue is ready
