### ISSUE TITLE
Project List/Detail Pages

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#893]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We require 2 new pages; a list of all projects, and a Project detail view - that shows the datasets attached to it.

We can use the same pattern we currently have for Datasets, and Scan Reports. With a layout, and table structure.
Fetching code already exists for the endpoints to fetch projects, and to fetch datasets.

### Acceptance Criteria

- [ ] A page to show a list of the users projects
- [ ] A page to show a project detail, with its relevant datasets.

### Tasks

- [ ] New page for listing projects `/projects`
- [ ] New table for rendering the list of projects
- [ ] New layout for a project detail `projects/[id]/layout.tsx`
- [ ] New page for project detail
- [ ] Add `projects` to the app navigation

### Confirm creation

- [x] This issue is ready
