### ISSUE TITLE
Add large file (Scan Report) validation

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/carrot-mapper#901]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Currently there is a limit to the file size of a Scan Report that can be uploaded, this is set in the application configuration.

But if a Scan Report larger than this is uploaded, the upload will "silently" fail - and not give validation to the user. To the point of - the Scan Report is actually created, but will fail, and the user is not told why.

Created from
#857 

### Acceptance Criteria

- [ ] When a larger Scan Report than allowed is uploaded, it should fail, and the user should be told why

### Tasks

- [ ] Add validation on filesize in the API POST Scan Report

### Confirm creation

- [x] This issue is ready
